services:
  - type: web
    name: pos-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_server:app
    pythonVersion: "3.11.4"
    envVars:
      - key: DATABASE_URL
        sync: false
